version: "3.8"

services:
  mytask-api:
    image: ${DOCKER_REGISTRY-}mytask-api:v1
    container_name: mytask-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass@*****
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/mytask.pfx
    ports:
      - "8081:80"
      - "8082:443"
    networks:
      - auth-network
    depends_on: 
      - mongodb
    volumes:
      - ~/.aspnet/https:/https:ro
  
  postgres:
    container_name: postgres
    image: library/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: keycloak_db
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - auth-network

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
    ports:
      - "8484:8080"
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
    networks:
      - auth-network

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=mytask
    volumes:
      - type: bind
        source: ./data
        target: /data/db
        
  config-server:
    image: steeltoeoss/config-server
    ports:
      - '8888:8888'
    command: --spring.cloud.config.server.git.uri=https://github.com/VladislavPiunov/my-config.git --spring.cloud.config.server.git.default-label=main

networks:
  auth-network:
    driver: bridge